<?php

namespace IT\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getLatestMessages($number) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('m')
            ->from('ITUserBundle:Message', 'm')
            ->where('m.vu = false')
            ->orderBy('m.dateEnvoi', 'ASC')
            ->setMaxResults($number);
        return $qb->getQuery()->getResult();
    }
}
