<?php

namespace IT\InventoryBundle\Repository;

use DateTimeZone;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * listsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class inventairesRepository extends EntityRepository
{
    public function verifierMateriel($inventaire, $materiel)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('Count(l.id) as cnt')
            ->from('ITInventoryBundle:LineInventory', 'l')
            ->where('l.inventaire = :inventaire')
            ->setParameter('inventaire', $inventaire)
            ->andWhere('l.resource = :ressource')
            ->setParameter('ressource', $materiel);
        $query = $qb->getQuery();
        // On récupère les résultats à partir de la Query
        $resultats = $query->getArrayResult();
        $resultats=(int)$resultats[0]["cnt"] ;
        // On retourne ces résultats
        return $resultats;
    }

    public function verifierExistantMateriel($code)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('Count(m.id) as cnt')
            ->from('ITResourceBundle:Ressource', 'm')
            ->where('m.bar_code = :code')
            ->setParameter('code', $code) ;
        $query = $qb->getQuery();
        // On récupère les résultats à partir de la Query
        $resultats = $query->getArrayResult();
        $resultats=(int)$resultats[0]["cnt"] ;
        // On retourne ces résultats
        return $resultats;
    }


}
